dot sortgraph1.dot -Tsvg -o sortgraph1.svg
dot sortgraph2.dot -Tsvg -o sortgraph2.svg
dot sortgraph1b.dot -Tsvg -o sortgraph1b.svg
dot sortgraph.dot -Tsvg -o sortgraph.svg
dot sortgraph4.dot -Tsvg -o sortgraph4.svg
dot sortgraph5.dot -Tsvg -o sortgraph5.svg
dot sortgraph6.dot -Tsvg -o sortgraph6.svg
dot sortgraph7.dot -Tsvg -o sortgraph7.svg
dot sortgraph8.dot -Tsvg -o sortgraph8.svg
